#!/usr/bin/env bash
# Configure your domain zone

if [ "$#" = 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        record=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        dest=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')

        echo "The subdomain $subdomain is a $record record and points to $dest"
    done
elif [ "$#" = 2 ]; then
    record=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    dest=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')

    echo "The subdomain $2 is a $record record and points to $dest"
fi
