#!/usr/bin/env bash
#  Install nginx web server

# update the OS
apt-get update -y

# install nginx
apt-get install nginx -y

# add html to index in www/html dir
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
