#!/usr/bin/env bash
# Install nginx web server

# update the OS
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

# add html to index in www/html dir
echo "Hello World!" | sudo tee /var/www/html/index.html

# reload server
sudo service nginx restart
