#!/usr/bin/env bash
# configure the HTTP response header of each web server

# update OS
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

# configure www/html files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err_404.html

# config file
config="
# Default server configuration
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        add_header X-Served-By $hostname;

        root /var/www/html;
        index index.htm index.html index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        location /redirect_me {
                return 301 https://google.com/;
        }

        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
}
"

echo "$config" | sudo tee /etc/nginx/sites-available/default 

# reload nginx server
sudo service nginx restart
