#!/usr/bin/env bash
# configure the HTTP response header of each web server

config_file=/etc/nginx/sites-available/default

sudo sed -i "/location \/ {/a \\        \\tadd_header X-Served-By \$hostname;" "$config_file"
