#!/usr/bin/env bash
# configure the HTTP response header of each web server

# update OS
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

# configure www/html files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# configure the server, with redirect settings
server_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name johnlivingprooff.tech;

    location /redirect_me {
        return 301 https://google.com/; # Change the URL to your desired destination
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
"

# add configured redirect
echo "$server_config" | sudo tee /etc/nginx/sites-available/default

# reload nginx server
sudo service nginx restart
