#!/usr/bin/env bash
# configuring the HAproxy for loadbalancer

# use super user
sudo su

# update OS
apt-get update -y
apt upgrade -y

# install haproxy2.8-stable(LTS)
# sudo apt-get install --no-install-recommends software-properties-common
# echo | sudo add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy -y

# configuring HAproxy
config="
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server web_server_1 100.25.162.17:80 check
        server web_server_2 100.25.131.228:80 check
"
haproxy_cfg="/etc/haproxy/haproxy.cfg"

# append configurations
echo "ENABLED=1" | tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | tee -a /etc/default/haproxy
echo "$config" | tee -a "$haproxy_cfg"

# restart the haproxy
service haproxy restart
