#!/usr/bin/env bash
# 0. Nginx likes port 80
sudo apt-get update -y
sudo apt-get install nginx -y
sed -i 's/8080 default_server/80 default_server/' /etc/nginx/sites-available/default
sudo service nginx restart