#!/usr/bin/env bash
# lists all currently running processes

# echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps aux --forest | awk '{printf "%-16s%-10s%-10s%-10s%-15s%-16s%-8s%-6s%-6s%-10s%s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
