#!/usr/bin/env bash
# lists only the current processes with the bash command

ps aux --forest | awk '$11 ~ /bash/ {printf "%-16s%-10s%-10s%-10s%-15s%-16s%-8s%-6s%-6s%-10s%s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
