#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# to tell a story

while IFS=: read -r user pass uid gid info dir login; do
    echo "The user $user is part of the $gid gang, lives in $dir and rides $login. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd
